const nodemailer = require("nodemailer");

class EmailService {
  constructor() {
    this.transporter = null;
    this.toEmail = null;
    this.fromEmail = null;
  }

  init(smtpUser, smtpPass, toEmail) {
    this.fromEmail = smtpUser;
    this.toEmail = toEmail;
    this.transporter = nodemailer.createTransport({
      service: "gmail",
      auth: { user: smtpUser, pass: smtpPass }
    });
    console.log('[Email] Service initialized');
  }

  isReady() { return !!(this.transporter && this.toEmail); }

  async send({ subject, html, to = null, attachments = null }) {
    if (!this.isReady()) throw new Error("Email not configured");
    const result = await this.transporter.sendMail({
      from: `"TaskPilot" <${this.fromEmail}>`,
      to: to || this.toEmail,
      subject,
      html,
      attachments: attachments || []
    });
    console.log(`[Email] Sent: ${result.messageId}`);
    return result;
  }

  async sendTaskResult(taskTitle, prompt, aiResponse, position, total) {
    const duration = new Date().toLocaleTimeString();
    const html = `
    <html style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333;">
      <body style="background: #f5f5f5; padding: 20px;">
        <div style="max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden;">
          
          <!-- Header -->
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center;">
            <h1 style="margin: 0; font-size: 28px;">✅ TaskPilot — Task Complete</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9; font-size: 14px;">Task ${position}/${total}</p>
          </div>

          <!-- Content -->
          <div style="padding: 30px;">
            <h2 style="color: #667eea; margin-top: 0;">📋 ${taskTitle}</h2>

            <div style="background: #f9f9f9; padding: 15px; border-left: 4px solid #667eea; margin: 20px 0; border-radius: 4px;">
              <p style="margin: 0 0 10px 0; color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 1px;">Prompt</p>
              <pre style="margin: 0; white-space: pre-wrap; word-wrap: break-word; color: #333; font-family: 'Courier New', monospace; font-size: 13px;">${this.escapeHtml(prompt)}</pre>
            </div>

            <div style="background: #f0f7ff; padding: 15px; border-left: 4px solid #4CAF50; margin: 20px 0; border-radius: 4px;">
              <p style="margin: 0 0 10px 0; color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 1px;">AI Response</p>
              <div style="margin: 0; white-space: pre-wrap; word-wrap: break-word; color: #333; font-family: 'Courier New', monospace; font-size: 13px; max-height: 400px; overflow-y: auto; line-height: 1.6;">${this.escapeHtml(aiResponse)}</div>
            </div>

            <div style="background: #f5f5f5; padding: 15px; border-radius: 4px; margin: 20px 0;">
              <p style="margin: 5px 0; color: #666; font-size: 13px;"><strong>Executed:</strong> ${duration}</p>
              <p style="margin: 5px 0; color: #666; font-size: 13px;"><strong>Status:</strong> <span style="color: #4CAF50; font-weight: bold;">Completed</span></p>
            </div>
          </div>

          <!-- Footer -->
          <div style="background: #f9f9f9; padding: 20px; text-align: center; border-top: 1px solid #ddd;">
            <p style="margin: 0; color: #999; font-size: 12px;">
              Generated by TaskPilot at ${new Date().toISOString()}<br/>
              <a href="https://github.com/beingsahilsharma13/taskpilot" style="color: #667eea; text-decoration: none;">Learn more →</a>
            </p>
          </div>
        </div>
      </body>
    </html>`;

    return this.send({ subject: `✅ TaskPilot — ${taskTitle}`, html });
  }

  escapeHtml(unsafe) {
    return unsafe
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
}

module.exports = new EmailService();
